### ISSUE TITLE
Test against compatible marketplace in Testnet

### ISSUE THREAD

**Issue by autogestion** [MjolNear/simple-nft-contract#1]
Is there version of MjolNear in testnet? 
and will it work with mintbase marketplace? which is deployed to testnet https://testnet.mintbase.io/

**Comment by olegggatttor** [comment]
Hey! Currently there is not. We are going to add it soon (at least like a contract, without website). If you want to try it now you can deploy it by yourself from sources. About mint base: yes it will work.
